version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_DATABASE=
    expose:
      - "3307"
    ports:
      - '3307:3306'
    volumes:
      - db:/var/lib/mysql
    networks:
      - app-tier
  app:
    depends_on:
      - db
    build:
      context: .
      dockerfile: Dockerfile
    container_name: typescript-web-api
    image: typescript-web-api
    restart: always
    networks:
      - app-tier
    ports:
      - 3456:3456
    environment:
      - PORT=3456
      - SECRET_KEY=@SECRET_KEY
      - TYPE=mysql
      - HOST=db
      - DATABASE_PORT=3306
      - DATABASE_USERNAME=
      - DATABASE_PASSWORD=
      - DATABASE_NAME=
      - DEFAULT_ADMINSTRATOR_USER_ID=@DEFAULT_ADMINSTRATOR_USER_ID
      - DEFAULT_ADMINSTRATOR_USER_NAME=@DEFAULT_ADMINSTRATOR_USER_NAME
      - DEFAULT_ADMINSTRATOR_USER_EMAIL=@DEFAULT_ADMINSTRATOR_USER_EMAIL
      - DEFAULT_ADMINSTRATOR_PROFILE_ID=@DEFAULT_ADMINSTRATOR_PROFILE_ID
      - DEFAULT_USER_PROFILE_ID=@DEFAULT_USER_PROFILE_ID
      - DEFAULT_USER_PROFILE_NAME=@DEFAULT_USER_PROFILE_NAME
      - DEFAULT_CONFIRMATION_TYPE_USER_ID=@DEFAULT_CONFIRMATION_TYPE_USER_ID
      - DEFAULT_CONFIRMATION_TYPE_USER_NAME=@DEFAULT_CONFIRMATION_TYPE_USER_NAME
      - URL_API_DOLLAR_RATE=https://economia.awesomeapi.com.br/json/last
volumes:
  db:
    driver: local
networks:
  app-tier:
    driver: bridge